CREATE DATABASE QLHH
ON
(
    NAME = QLHH_DATA,
    FILENAME = 'D:\00.DATA\QLHH.mdf',
    SIZE = 10,
    MAXSIZE = 50,
    FILEGROWTH = 5
)
LOG ON
(
    NAME = LAB02_log,
    FILENAME = 'D:\00.DATA\QLHH_log.ldf',
    SIZE = 5MB,
    MAXSIZE = unlimited,
    FILEGROWTH = 5MB
);
GO

USE QLHH
GO
CREATE TABLE dbo.VATTU(
	MAVTU char(4) NOT NULL,
	TENVTU nvarchar(100) NOT NULL UNIQUE,
	DVTINH nvarchar(10) NULL CONSTRAINT DF_DVTINH DEFAULT(''),
	PHANTRAM REAL NULL CONSTRAINT  CK_PHANTRAM CHECK(PHANTRAM>=0 AND PHANTRAM <=100 ),
	CONSTRAINT PK_VATTU PRIMARY KEY (MAVTU)
)
GO
CREATE TABLE dbo.NHACC(
	MANHACC char(3) NOT NULL CONSTRAINT PK_NHACC PRIMARY KEY,
	TENNHAC nvarchar(100) NOT NULL UNIQUE,
	DIACHI nvarchar(200) NOT NULL UNIQUE,
	DIENTHOAI nvarchar(20) NULL CONSTRAINT  DF_DIENTHOAI DEFAULT(N'Chưa có'),
)	
GO

CREATE TABLE dbo.DONDH(
	SODH char(4) NOT NULL CONSTRAINT PK_DONDH PRIMARY KEY,
	NGAYDH datetime CONSTRAINT DF_NGAYDH DEFAULT(GETDATE()),
	MANHACC char(3) NOT NULL,
	
)
GO
CREATE TABLE dbo.CTDONDH(
	SODH char(4) NOT NULL,
	MAVTU char(4) NOT NULL,
	SLDAT int NOT NULL CONSTRAINT  CK_SLDAT CHECK(SLDAT>0),
	CONSTRAINT FK_CTDONDH_DONDH_SODH FOREIGN KEY (SODH) REFERENCES DONDH(SODH)
		ON UPDATE CASCADE 
		ON DELETE NO ACTION,
	CONSTRAINT FK_CTDONDH_VATTU_MAVTU FOREIGN KEY (MAVTU) REFERENCES VATTU(MAVTU)
		ON UPDATE CASCADE 
		ON DELETE NO ACTION,
	CONSTRAINT PK_CTDONDH PRIMARY KEY (SODH,MAVTU)	 
)
GO
CREATE TABLE dbo.PNHAP(
	SOPN char(4) NOT NULL CONSTRAINT PK_PNHAP PRIMARY KEY,
	NGAYNHAP datetime CONSTRAINT DF_NGAYNAP DEFAULT(GETDATE()),
	SODH char(4) NOT NULL CONSTRAINT FK_PNHAP_DONDH_SODH FOREIGN KEY (SODH) REFERENCES DONDH(SODH)
		ON UPDATE CASCADE 
		ON DELETE NO ACTION,
)
GO

 CREATE TABLE dbo.CTPNHAP(
	SOPN char(4) NOT NULL ,
	MAVTU char(4) NOT NULL,
	SLNHAP int NOT NULL CONSTRAINT  CK_SLNHAP CHECK(SLNHAP>0),
	DGNHAP money NOT NULL CONSTRAINT  CK_DGNHAP CHECK(DGNHAP>0),
	CONSTRAINT FK_CTPNHAP_VATTU_MAVTU FOREIGN KEY (MAVTU) REFERENCES VATTU(MAVTU)
		ON UPDATE CASCADE 
		ON DELETE NO ACTION,
	CONSTRAINT FK_CTPNHAP_PNHAP_SOPN FOREIGN KEY (SOPN) REFERENCES PNHAP(SOPN)
		ON UPDATE CASCADE 
		ON DELETE NO ACTION,
	CONSTRAINT PK_CTPNHAP PRIMARY KEY (SOPN,MAVTU)	 
)
GO

CREATE TABLE dbo.PXUAT(
	SOPX char(4) NOT NULL CONSTRAINT PK_PXUAT PRIMARY KEY,
	NGAYXUAT datetime CONSTRAINT DF_NGAYXUAT DEFAULT(GETDATE()),
	TENKH nvarchar(100) NOT NULL,
)
GO

CREATE TABLE dbo.CTPXUAT(
	SOPX char(4) NOT NULL,
	MAVTU char(4) NOT NULL,
	SLXUAT int NOT NULL CONSTRAINT  CK_SLXUAT CHECK(SLXUAT>0),
	DGXUAT money NOT NULL CONSTRAINT  CK_DGXUAT CHECK(DGXUAT>0),
	CONSTRAINT FK_CTPXUAT_VATTU_MAVTU FOREIGN KEY (MAVTU) REFERENCES VATTU(MAVTU)
		ON UPDATE CASCADE 
		ON DELETE NO ACTION,
	CONSTRAINT FK_CTPXUAT_PNHAP_SOPX FOREIGN KEY (SOPX) REFERENCES PNHAP(SOPN)
		ON UPDATE CASCADE 
		ON DELETE NO ACTION,
	CONSTRAINT PK_CTPXUAT PRIMARY KEY(SOPX,MAVTU)
 )

GO

 CREATE TABLE dbo.TONKHO(
	NAMTHANG char(4) NOT NULL,
	MAVTU char(4) NOT NULL,
	SLDAU int NOT NULL CONSTRAINT  CK_SLDAU CHECK(SLDAU>0),
	TONGSLN int NOT NULL CONSTRAINT  CK_TONGSLN CHECK(TONGSLN>0),
	TONGSLX int NOT NULL CONSTRAINT  CK_TONGSLX CHECK(TONGSLX>0),
	SLCUOI int NOT NULL,
	CONSTRAINT FK_TONKHO_VATTU_MAVTU FOREIGN KEY (MAVTU) REFERENCES VATTU(MAVTU)
		ON UPDATE CASCADE 
		ON DELETE NO ACTION,
	CONSTRAINT PK_TONKHO PRIMARY KEY(NAMTHANG,MAVTU)
 )
 GO

 CREATE FUNCTION fn_TONKHO_SLCUOI
( 
	@NAMTHANG CHAR(4),
	@MAVTU CHAR(4)
)
RETURNS INT
AS
BEGIN
    DECLARE @SLCUOI INT;
    SELECT @SLCUOI = SLDAU+ TONGSLN -TONGSLX FROM [dbo].[TONKHO] WHERE NAMTHANG = @NAMTHANG and MAVTU = @MAVTU
    RETURN @SLCUOI;
END;
GO


ALTER TABLE TONKHO
DROP COLUMN SLCUOI
GO
ALTER TABLE TONKHO
ADD SLCUOI AS DBO.fn_TONKHO_SLCUOI(NAMTHANG,MAVTU)
GO